build: false

environment:
  PYTHON: "C:\\myminiconda3"
  matrix:
    - PY: 3.7
    - PY: 3.8

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  # Add path, activate `conda` and update conda.
  - set URL="https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe"
  - curl -fsS -o miniconda3.exe %URL%
  - start /wait "" miniconda3.exe /InstallationType=JustMe /RegisterPython=0 /S /D=%PYTHON%

  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - call %PYTHON%\Scripts\activate

  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update conda --quiet
  - conda config --add channels conda-forge --force
  - conda config --set channel_priority strict
  - conda config --set safety_checks disabled

  # Create the test env.
  - conda create --name TEST python=%PY% --file requirements.txt --file requirements-dev.txt
  - activate TEST

  # Debug.
  - conda info --all
  - conda list

test_script:
  - pip install -e . --no-deps --force-reinstall
  - pytest -n 2 -rxXs -m "not headless" tests
