name: Tarball Tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        activate-conda: false
        conda-channels: conda-forge

    - name: Python 3
      shell: bash -l {0}
      run: |
        conda create --name TEST python=3 pip --file requirements.txt --file requirements-dev.txt
        source activate TEST
        pip install -e . --no-deps --force-reinstall
        conda info --all
        conda list

    - name: Tarball tests
      shell: bash -l {0}
      run: |
        source activate TEST
        pip wheel . -w dist --no-deps
        check-manifest --verbose
        twine check dist/*
