name: Headless Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Micromamba
      uses: mamba-org/provision-with-micromamba@v14
      with:
        environment-file: false

    - name: Python 3
      shell: bash -l {0}
      run: |
        micromamba create --name TEST python=3 pip --file requirements.txt --file requirements-dev.txt --channel conda-forge
        micromamba activate TEST
        pip install -e . --no-deps --force-reinstall

    - name: Tests
      shell: bash -l {0}
      run: |
        micromamba activate TEST
        pytest -vv -rxs tests -m "headless"
